---

- hosts: all
  become: true
  tasks:

  - name: Install updates (Ubuntu, Debian)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Install updates (RHEL, Rocky)
    yum:
      update_cache: yes
      update_only: yes
    when: ansible_distribution in ["Rocky", "Redhat"]
