---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (RHEL)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install Apache and php Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install Apache and php Rocky
    tags: apache,rocky,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Copy default site html file
    tags: apache,apache2, httpd
    copy:
      src: default_site.html
      dest: /var/ww/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb (RHEL)
    tags: rocky,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba
    tags: samba
    package:
      name: samba
      state: absent
