- name: install httpd package (Redhat)
  tags: apache,redhat,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution_file_variety == "RedHat"

- name: start and enable https (Redhat)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_disribution_file_variety == "RedHat"

- name: install apache2 package (Debian)
  tags: apache,apache2,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution_file_variety == "Debian"

- name: change email address for admin
  tags: apache,redhat,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin nick.miller724@gmail.com
  when: ansible_distribution_file_variety == "RedHat"

- name: restart httpd (Redhat)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.change

- name: copy html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
