- name: install mariadb server package (RedHat)
  tags: redhat,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution_file_variety == "Redhat"

- name: install mariadb server package (Debian)
  tags: db,mariadb,debian
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution_file_variety == "Debian"
